version: '3'
services:
  postgresql:
    container_name: transcendence-db
    image: postgres:15
    environment:
      POSTGRES_USER: '42ladies'
      POSTGRES_PASSWORD: '42'
    ports:
      - "3306:3306"